// Generated by CoffeeScript 1.9.3
(function() {
  var weatherReportCoffee;

  weatherReportCoffee = require('../src/weatherReport');

  weatherReportCoffee.readFile('input.txt', weatherReportCoffee.splitIDs);

  exports.displayResults = function(sortedContent) {
    var i, len, n, results;
    console.log('\nCity		State	Temperature');
    results = [];
    for (i = 0, len = sortedContent.length; i < len; i++) {
      n = sortedContent[i];
      results.push(console.log('%s		%s	%s \n', n.city, n.state, n.temp));
    }
    return results;
  };

}).call(this);
